# Generated by Django 4.2.2 on 2023-06-19 13:13

import django.core.validators
from django.db import migrations, models
import ep_200623.expenses_tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), ep_200623.expenses_tracker.models.validate_letters])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), ep_200623.expenses_tracker.models.validate_letters])),
                ('budget', models.FloatField(default=0.0, validators=[ep_200623.expenses_tracker.models.below_zero_validator])),
                ('profile_image', models.ImageField(blank=True, default='user.png', null=True, upload_to='', validators=[ep_200623.expenses_tracker.models.max_size_validator])),
            ],
        ),
    ]
