# Generated by Django 4.2.2 on 2023-06-20 06:23

from django.db import migrations, models
import ep_200623.expenses_tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0002_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/user.png', null=True, upload_to='', validators=[ep_200623.expenses_tracker.models.max_size_validator]),
        ),
    ]
